# Exported from Render on 2025-01-25T18:06:04Z
services:
  - type: web
    name: Football46
    runtime: node
    repo: https://github.com/coolzhz/aipfootbal
    plan: free
    envVars:
      - key: .env
        sync: false
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
version: "1"
